### ISSUE TITLE
Help translate this app

### ISSUE THREAD

**Issue by fgl27** [fgl27/smarttv-twitch#1]
This app is originally write in [English](https://github.com/fgl27/SmartTwitchTV/blob/master/app/languages/en_US.js) is current not translated.

Anyone can translate to a new language or improve current translations included the original in English as I the developer didn't born speaking it.

If you wanna to translate this to yours language is very simple just translate this file [en_US.js](https://github.com/fgl27/SmartTwitchTV/blob/master/app/languages/en_US.js) from English to yours.

You can share the translated file here, by simply drag and drop, make a pull request or just email the developer @fgl27 (check the email in guithub bio).

If you have any doubt about the translation you can also post here or send it by email.

Any other type of help with this app is appreciated.

**Comment by MarconiGRF** [comment]
I'll help you translate the en_US.js file.

**Comment by Aintheone** [comment]
I glad to help, to translate to hungarian is u wish :)

**Comment by DerSani1988** [comment]
@fgl27 is it possible to test a translation? I Tried to add in /app/language, edited the main.js and settings.js but the emulation doesn't start, did I miss something?

**Comment by fgl27** [comment]
You can install the app from the repository folder by, fork, clone, import the cloned folder as a file system to a new app, and install. you can make the changes on top of the **en_US.js** so it loads by default and you see, I deal with the settings changes later don't wonry.

If you don't use git just makes the download and install from here:
https://github.com/fgl27/smarttv-twitch/archive/master.zip

And do the same "changes on top of the **en_US.js** so it loads by default and you see"

Use the ladybug icon to install the app, in case the app doesn't open is because some line is wrong in the file and the log will warn about with line.

the emulator is the same process, but is better to do on the tv, the above link will not uninstall the released version of the app you already have installed will just install side by side.

**Comment by fgl27** [comment]
here is a sample on how to fully add a language:
https://github.com/fgl27/smarttv-twitch/commit/7b6f867cb38ef62a6e7fc7c0eaf46acebc938329#diff-1b40fc887130f4b9bfa361fe3f795211

but I do that no problem, just a sample.

**Comment by DerSani1988** [comment]
@fgl27 please find attached the German translation (de_DE) - Deutsch [DE]:

[de_DE.zip](https://github.com/fgl27/smarttv-twitch/files/3143688/de_DE.zip)

Kindly note some small changes are necessary on your side: 

1) Suggestion: This **comma** should be added to the other language files to provide more flexibility for upcoming translations an would look cleaner in German translation:
![_Channel_colon](https://user-images.githubusercontent.com/25698122/57168014-3af99000-6e00-11e9-9e39-8dbd21793766.jpg)

2) As above:
![_main](https://user-images.githubusercontent.com/25698122/57168017-3b922680-6e00-11e9-9ced-47cff1032b4a.jpg)

3) Suggestion: Date variable for display day without "/":
![_date](https://user-images.githubusercontent.com/25698122/57168016-3b922680-6e00-11e9-9f41-60645ce24cdd.jpg)


4) Another **comma** and the bottom menu should be resized:
![_player](https://user-images.githubusercontent.com/25698122/57168018-3b922680-6e00-11e9-8d15-76e6d0d47085.jpg)

5) Dot needs to me removed (if it is not a lot of work)
![_playermanual](https://user-images.githubusercontent.com/25698122/57168019-3b922680-6e00-11e9-815e-c5ee3013e58f.jpg)

Something further: A few vars are not translated due to logical reason e.g. "Following" and some other vars couldn't be found in app so the context wasn't clear.

If I see something in the future I can improve (logics, typos) I'll let you know.

Cheers

**Comment by fgl27** [comment]
I push yours translation you can finished if you wanna by downloading from here
https://github.com/fgl27/smarttv-twitch/archive/master.zip
and updating the de_DE.js and sharing it here (you can just drag the file here no need to zip btw)

Strings that you will not translate you don't make it "", you just "comment it out" like this
https://github.com/fgl27/smarttv-twitch/blob/master/app/languages/de_DE.js#L30

the word "for" doesn't translate to |, if it doesn't have a proper way to translatable try to explain to me why is that.

In relation to yours numbers...

1. 2. and 5. you miss translate some things that is way looks odd's for you, now that the  language is there you can change to english refresh the screen see how is in english go back change to German refresh again see what is missing to change and do it, or not leave as is but don't add empty strings

3. yes a space there looks better

4. I don't understand the resize, you mean removed?...I fix the visual glitches.

The string "Following" is there next to the heart on the bottom on the player and in the Agame section, but only shows if you add a user and is Following the streamer/game, I fix the odd looking layouts there so you can see it now, may there be more places that look odd if you find let me know, as on differents tvs things may look a little different.

thanks no rush.

**Comment by DerSani1988** [comment]
Sharing the .js file as an attachment was not possible.

**Regarding 1 and 2:**
I've removed the "for" value and replaced with "|" for better looking
![Screenshot_6](https://user-images.githubusercontent.com/25698122/57176060-87ba8680-6e53-11e9-9f2d-98fb4cf913ac.jpg)

**Regarding 5:**
I've translated the needed information compact and overseeable. Without changing the meaning.

**Regarding 4:**
I mean the visual issue caused by the length of the German words (i think this is what you mean with visual glitch)

I'll check your update soon and respond

**Comment by fgl27** [comment]
I wanna to keep things familiar this is how the twitch player looks
![Screenshot from 2019-05-04 09-46-13](https://user-images.githubusercontent.com/13755892/57179217-b2a3db00-6e51-11e9-9b15-276c26a6dc28.png)

that is way the "playing" and "for" words are there, don't worry if looks odd I fix later

Replace the file ext to txt or zip it with ever is easy, I didn't know they limited the file type

The "ago" I will remove.

**Comment by DerSani1988** [comment]
So it's  your app and i respect your wishes. I've added the "playing" and "for" translation.

> //STR_CONTROLS_MAIN_7 = ""; 
> //STR_CONTROLS_MAIN_11 = ""; 
> //STR_CONTROLS_PLAY_16 = ""; 
are not needed - as I mentioned before, the translation is not word by word. The meaning is still the same, only may reduced to the important things to prevent a confusing wall of text. (The last one did not work on any tested TV nor on simulation, and was removed)

> //STR_STARTED = "";
Is grammatically wrong (if translated) and needs to be removed.
![_started](https://user-images.githubusercontent.com/25698122/57181031-dfc2ae80-6e8e-11e9-997b-109aff4e6d7c.jpg)

The about section I wanted to keep original, so as many apps do, and it's easier for you to update. I commented out.

Hope above explanation will help you to understand why I do things this way, if you have any questions, please feel free to ask.

Please find attached the updated language file.
[de_DE_v2.zip](https://github.com/fgl27/smarttv-twitch/files/3144494/de_DE_v2.zip)

If you have another updated version please let me know I'll check once again before rolling out in the main version.

**Comment by fgl27** [comment]
Ok I move the missing translation to the bottom
https://github.com/fgl27/smarttv-twitch/blob/master/app/languages/de_DE.js#L216-L219

So you or anyone can update they in the future.

If something looks odd/misplaced on yours end let me know.

**Comment by DerSani1988** [comment]
I've reviewed the file and made two small changes [here](https://github.com/fgl27/smarttv-twitch/compare/master...DerSani1988:patch-1). I Think nothing else i can provide at this point. Will check next days spending time using the app.

Thank you @fgl27  for your development and providing this great app, I appreciate your work!

**Comment by fgl27** [comment]
you welcome, thank you for the help I remove the "am" by mistake i will keep without the ":" makes sense with or without.

**Comment by pi0ne3r** [comment]
[ru_Ru.zip](https://github.com/fgl27/smarttv-twitch/files/3166828/ru_Ru.zip)
Added Russian language support, please proceed with it!

**Comment by fgl27** [comment]
@pi0ne3r I will check and push it later I let you know so you can re-check after I do.

**Comment by Xynetha** [comment]
Spanish translation added.

**Comment by fgl27** [comment]
Ok I push it all later thanks.

**Comment by fgl27** [comment]
@pi0ne3r can you find small similar translations? for:
STR_FEATURED = 'Featured';
STR_USER = "User ";

If possible share here I update the ru_RU for those.

I push the es and ru translation, @Xynetha @pi0ne3r let me know if anything doesn't look OK.

**Comment by pi0ne3r** [comment]
> @pi0ne3r can you find small similar translations? for:
> STR_FEATURED = 'Featured';
> STR_USER = "User ";
> 
> If possible share here I update the ru_RU for those.
Thanks @fgl27 , I attached edited translation with few replaces for more shortres words
[ru_Ru.zip](https://github.com/fgl27/smarttv-twitch/files/3171596/ru_Ru.zip)

**Comment by fgl27** [comment]
@pi0ne3r @Xynetha I push all the changes, thanks for the help.

**Comment by Rossano95** [comment]
Hello, I have updated the traduction. It only needed a few strings.
[it_IT.zip](https://github.com/fgl27/smarttv-twitch/files/3414098/it_IT.zip)

**Comment by fgl27** [comment]
Push it thanks.

**Comment by fgl27** [comment]
I made a new app, and because of that remove all translations.

If anyone that did on the past a translation can do it again I will be thankful.

To test your new translation the simple way is to download the source 

https://github.com/fgl27/smarttv-twitch/archive/master.zip

change the default language file 

https://github.com/fgl27/smarttv-twitch/blob/master/app/languages/en_US.js and 

Install the source as a new app and test.

If anyone found a bug on the new app open a separated issue.

**Comment by Rossano95** [comment]
I need to do all again or the strings are the same?
________________________________
Da: Felipe Leon <notifications@github.com>
Inviato: giovedì 1 agosto 2019 20:25
A: fgl27/smarttv-twitch <smarttv-twitch@noreply.github.com>
Cc: Rossano95 <rossanololly@live.it>; Comment <comment@noreply.github.com>
Oggetto: Re: [fgl27/smarttv-twitch] Help translate this app (#1)


I made a new app, and because of that remove all translations.

If anyone that did on the past a translation can do it again I will be thankful.

To test your new translation the simple way is to download the source

https://github.com/fgl27/smarttv-twitch/archive/master.zip

change the default language file

https://github.com/fgl27/smarttv-twitch/blob/master/app/languages/en_US.js and

Install the source as a new app and test.

If anyone found a bug on the new app open a separated issue.

**Comment by fgl27** [comment]
This is what I have change from the en_US.js 

https://github.com/fgl27/smarttv-twitch/commit/cfaf5ba79c3067e8d70849a1606232dfff1eeea2

Is not all but was too many changes making the translation incompatible. I add most new strings on the bottom, and change and remove some old ones.

Maybe you can understand by reading the commit and update only what have change, if not just and you can translate just do it all.

**Comment by Rossano95** [comment]
Is there a way to automatically import the strings from the old file and then add the new one? Now I  have no time for this. Maybe in september.
________________________________
Da: Felipe Leon <notifications@github.com>
Inviato: sabato 3 agosto 2019 03:58
A: fgl27/smarttv-twitch <smarttv-twitch@noreply.github.com>
Cc: Rossano95 <rossanololly@live.it>; Comment <comment@noreply.github.com>
Oggetto: Re: [fgl27/smarttv-twitch] Help translate this app (#1)


This is what I have change from the en_US.js

cfaf5ba<https://github.com/fgl27/smarttv-twitch/commit/cfaf5ba79c3067e8d70849a1606232dfff1eeea2>

Is not all but was too many changes making the translation incompatible. I add most new strings on the bottom, and change and remove some old ones.

Maybe you can understand by reading the commit and update only what have change, if not just and you can translate just do it all.

**Comment by fgl27** [comment]
OK you don't need to do.

**Comment by Rossano95** [comment]
I need to only a few more strings. For now it's pretty complete
[it_IT.zip](https://github.com/fgl27/smarttv-twitch/files/4007176/it_IT.zip)

**Comment by fgl27** [comment]
OK I see if I re-enable the function again tomorrow and test it. I let you know.

**Comment by Sam-arch99** [comment]
Where can I change the language? I've installed the app via your tutorial and it's working great on my Q90R!! Much love <3

**Comment by fgl27** [comment]
> Where can I change the language? I've installed the app via your tutorial and it's working great on my Q90R!! Much love <3

the app has 0 translations.

**Comment by Sam-arch99** [comment]
> 
> the app has 0 translations.

Oh ok, I thought that people already helped with the translation progress (e.g. German) and you already implemented those translations in the app.

**Comment by Rossano95** [comment]
I sended the italian translation. Of you enable It I can check of it's ok.

**Comment by fgl27** [comment]
That is no longer valid translation. I plan to update the app, so the strings have all changed.

**Comment by fgl27** [comment]
The day I release the next app version I'll open a new issue for this.

**Comment by eze92** [comment]
Just out of curiosity, is it possible to pass the translation that was made in the android version to this one? or will you have to re-translate from scratch?

**Comment by fgl27** [comment]
Everything general translation from Android will be reused...

Just some strings that are related to Samsung version that will be missing, but most people will not notice it when using the app.
