### ISSUE TITLE
Chat on live stream doesn't work 

### ISSUE THREAD

**Issue by Kurtzisa** [fgl27/smarttv-twitch#11]
In every live stream the chat doesn't work. 
I can see "chat: connecting to chat server" 
In the vod the chat work 

With or without logging with my account

**Comment by fgl27** [comment]
If the above doesn't help I will need you to grab a log of the issue (I explain the log part on a separated comment bellow)

Open the app check if version in about is 4.0.1.**042419** if is try the chat, if is not hold return key so the app force close and open again so it can update and try the chat...

If no good do the log as I will explain bellow

**Comment by fgl27** [comment]
from this link https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

you can see me explain how to make a log. Do that in doubt let me know.

**Comment by Kurtzisa** [comment]
Ok, i'll try, but Samsung forced to erase the app 2h ago.
I must reinstall the app

**Comment by fgl27** [comment]
OK let me know the chat result, and if the app keep uninstalling open a separated issue.

**Comment by Kurtzisa** [comment]
Hello Again
[Logs.txt](https://github.com/fgl27/smarttv-twitch/files/3117236/Logs.txt)
[error.txt](https://github.com/fgl27/smarttv-twitch/files/3117237/error.txt)

Every time i switch on the tv, the TV delete the app... 

But i have the log files. and the app is version 4.0.1.42519

**Comment by fgl27** [comment]
OK, you TV seems be uninstalling the app for some reason may be that samsung decides to block the app because twitch doesn't wanna it there...

try this zip and let me know if it doesn't have the uninstall issue

[release.zip](https://github.com/fgl27/smarttv-twitch/files/3117698/release.zip)

I will deal with the chat on next comment.

**Comment by fgl27** [comment]
can you open this link? on a web browser on a computer o phone...

https://www.nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=dakotaz&fade=false&bot_activity=true&prevent_clipping=false

where **dakotaz** is the channel chat, so you can change that workd if that streamer is offline so you can see chat for a live stream...

Because for some reason the link is be blocked I don't understand yet way. from the logs we have

	WebSocket network error: Certificato TLS inammissibile https://www.nightdev.com/hosted/obschat/?theme=bttv_blackchat&channel=dakotaz&fade=false&bot_activity=true&prevent_clipping=false
	WebSocket connection to 'wss://irc-ws.chat.twitch.tv' failed: WebSocket is closed before the connection is established. [native code]

I will do some checks and see what I can do, I already have be working on a separated live chat independednt from kapchat, so if you can open the kapchat on yours computer I just switch to the new live chat when I finish it.

**Comment by Kurtzisa** [comment]
I can open the link in my Android phone and work with a lot of streamer.

The old app or your app doesn't play the Ad during the stream, i think this is why Amazon doesn't want this app on tizen.

**Comment by Kurtzisa** [comment]
Is safe for you to work on this app?

**Comment by fgl27** [comment]
does the new zip app get uninstalled?

This app is registered on twitch developer site, they provide all the documentation and authentication keys fro this to work
is all documented here
https://dev.twitch.tv/docs/

When I ask samsung they told me the name was the issue in first place I request a name change and they told me any app that I released there don't matter the name will not be approved because amazon it self doesn't wanna any app with twitch content there, they have a official twitch Tizen app already but is not released globally I never was able to use and that is the issue. noting related how the app works as they never ever tested the app to know.

I will make the chat changes and after I push I let you know so you can test.

**Comment by fgl27** [comment]
@Kurtzisa I push above the chat changes the version now is **4.0.1.042519_2**

Teste that version and let me know the chat behavior and the uninstall issue also.

**Comment by S0und** [comment]
@fgl27 change your app name to ' for Twich'   This is absolutely crucial! Something like "SmartTV **for Twitch**". 

Also i highly suggest to state this in the description of the app:

**This app has no affiliation with Twitch Interactive, Inc.**

So you have to make sure that, your app doesn't looks like if it tries to pretend to be like the "official" Twitch app. My app was removed twice because of this, although early i was ripping them off hard. 

If they let you resubmit your app, use "SmartTV **for Twitch**" or something like that, but make sure you use "for Twitch" in the name.

**Comment by Kurtzisa** [comment]
@fgl27 the version is 4.TESTING, the application automatically uninstall after a few hours

the chat works only in the vod, it doens't work in live streaming. 

Why i'm buying a samsung tv? I'm searching on the internet, tizen is such a horrible os.

**Comment by fgl27** [comment]
@Kurtzisa I need you to install the zip I shared before this

[release.zip](https://github.com/fgl27/smarttv-twitch/files/3121515/release.zip)

If you are using the link for debuging that one doesn't have or the chat improve or the new app ID, and will show version as " 4.TESTING".

so install the above and let me know the result on that.

**Comment by fgl27** [comment]
@S0und I don't wanna anymore released the app in the samsung tizen store, is not a simple name change

![Screenshot from 2019-04-26 10-43-56](https://user-images.githubusercontent.com/13755892/56812195-c5def700-6810-11e9-9c32-362b79e06005.png)

Samsung doesn't allow anyone to share a app there without they have check everything that the app does, they tested my app contact Amazon and let they know of the app existence, they told me that, then after the above happen.

I personalty don't care I already move on to android and released the app there and is working just fine, I recomende anyone to move to android if they can stay away from tizen if yo can @Kurtzisa

**Comment by gad192** [comment]
Hy, I have the same problem with my tv (Samsung J6240). I've been following this thread since a couple of days.
The chat thing is still present even with your latest release.zip. But before it wrote the "connecting to chat" or something, now the chat is just blank.
[chatlogerror.txt](https://github.com/fgl27/smarttv-twitch/files/3124346/chatlogerror.txt)

But the bigger problem is the Uninstall thing for me. What I noticed: If I install your app then shutdown/hard restart the TV:
- if I use the SMART HUB button instantly (before the TV connects to the internet via WiFi) the app starts and keep running until I use the SMART HUB button again.
- if I wait for the TV to connect to the internet, and then using the SMART HUB button, it just instantly starts the uninstall process.

My guess: Samsung is using a script, which detects your app name Twitch (before TwitchTv), and the same thing is happening like with the unofficial Twitch app which was on Store, and recently got deleted. 

So would you try the easiest, and rename it to something else? I saw that you kinda tried it with the TwitchTv-Twitch rename, but just try it without the Twitch word.

Thanks

**Comment by fgl27** [comment]
@gad192 I can remove the name works with any name.

I was trying to see if was a ID thing, but maybe not.

Try this and let me know the result

[release.zip](https://github.com/fgl27/smarttv-twitch/files/3124368/release.zip)

The chat thing I don't have a fix now, the TV firmware doesn't support the way the app loads the live chat, I need to study alternatives that uses different method to see if that works I don't have any now so will take some time until I can learn how to.

If anyone has a chat only link that is different from https://www.nightdev.com/kapchat/ let me know so I can make a test app and see how they are different...

**Comment by gad192** [comment]
Just tried it, it still uninstalls. :(

**Comment by fgl27** [comment]
Try this if that doesn't work yours TV is doing it to any app user installed.

[release.zip](https://github.com/fgl27/smarttv-twitch/files/3124390/release.zip)


If that is the case this samsung app will also have that issue

[PlayerAVPlay.zip](https://github.com/fgl27/smarttv-twitch/files/3124391/PlayerAVPlay.zip)

If tno let me know.

**Comment by gad192** [comment]
Yeah, this is the case, it just uninstalls playeravplay aswell, Could be an option in the service menu for it?
Btw Im still in developer mode, but I tried without it a couple of days ago,and same thing happened.

**Comment by fgl27** [comment]
I have no idea I don't have a TV that has a option for that I don't think is a option maybe a TV bug. My apps are always there.

Have you try to uninstall apps you don't use?
maybe is a too much app installed thing.

**Comment by gad192** [comment]
I have only the preinstalled apps, which cannot be uninstalled.

**Comment by fgl27** [comment]
@gad192 install some apps from the app store and see if they stay.

Maybe is a stupid bug that Samsung created on trying to removing all twitch apps.

**Comment by DerSani1988** [comment]
@fgl27  It's me, again ^^ back to topic of this issue, can confirm no chat on live streams but in Vods

**Comment by fgl27** [comment]
I know, the live and vod chat aren't the same in many things one is how the content is accessed tizen 2.3 TV don't seem to have support for this

https://github.com/fgl27/smarttv-twitch/blob/master/app/thirdparty/reconnecting-websocket.js

I need to find a replacement that support old browsers as tizen 2.3 is based on old browsers, but I have no way to test if will work, so I need just to make a test app and hope it works, the day I find a api that may support old browser I share a test app.

**Comment by fgl27** [comment]
also anyone helped me on this

> If anyone has a chat only link that is different from https://www.nightdev.com/kapchat/ let me know so I can make a test app and see how they are different...

**Comment by DerSani1988** [comment]
@fgl27 something like this https://www.twitch.tv/popout/<Streamname>/chat ?

**Comment by fgl27** [comment]
No more like the one I share aka not from twitch it self, as twitch does things that only they can as only they have permission. 
I need to do something here anyone can.

Plus I don't know if that chant work on the app as is too lag, and the Tizen OS is already too lag, even if works is not usable as is not transparent simple to overlay thing.

**Comment by itspeaky** [comment]
Sorry about opening an entire new post. As I said on that post got the log saying "WebSocket connection to 'wss://irc-ws.chat.twitch.tv' failed: WebSocket is closed before the connection is established". App version 4.0.1.050419, TV: Samsung JU6400.
I guess it may be me that I cant connect to the irc servers? Not sure.

Thanks for the help.

**Comment by fgl27** [comment]
@itspeaky the "etc" I meant all... Tizen version: yours value TV: yours value FW: yours value

thanks

**Comment by itspeaky** [comment]
@fgl27 Tizen version 2.3, TV: UJU6400, FW: T-HKMDEUC-1530.1

**Comment by fgl27** [comment]
@itspeaky 

> I guess it may be me that I cant connect to the irc servers? Not sure.

Tizen 2.3 issue. The os doesnot have support I post it before https://github.com/fgl27/smarttv-twitch/issues/11#issuecomment-489372747_

I don't have access to a old TV so I can't test and fix on my side.

So I share a zip here the day I have something for you people here to test.
I will try something this weekend if works on Tizen 2.4 i share to see if help on 2.3

**Comment by itspeaky** [comment]
@fgl27 alright, all good. I'll keep checking for udaptes.
Thanks for the work and the answers.

**Comment by fgl27** [comment]
[smarttv-twitch-default.zip](https://github.com/fgl27/smarttv-twitch/files/3170578/smarttv-twitch-default.zip)

[smarttv-twitch-no_check.zip](https://github.com/fgl27/smarttv-twitch/files/3170579/smarttv-twitch-no_check.zip)

Install the above as a new project the process is the same as to install the release zip.

After let me know the result by name:
**smarttv-twitch-default** works or not
**smarttv-twitch-no_check** works or not

**Comment by itspeaky** [comment]
@fgl27 smarttv-twitch-default Doesnt work
smarttv-twitch-no_check Doesnt work

**Comment by fgl27** [comment]
@fgl27 can you log it
how to log https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

**Comment by itspeaky** [comment]
@fgl27 for some reason I cant get the log to work like the other day, I get this error when I select Debug As.
![errorlog](https://user-images.githubusercontent.com/50504232/57650510-451f4980-75cb-11e9-88a6-7ff87544f8d4.png)

**Comment by fgl27** [comment]
Try to uninstall manually, by finding the app in the "apps" app holding select and click delete

**Comment by itspeaky** [comment]
@fgl27 there isnt any app there related to any of this on the "apps" section. In fact, I get my app deleted everytime I restart the TV. I know there is another post about that problem but I havent messed with that yet.

**Comment by fgl27** [comment]
None of those logs are from the zip I share here
the zip I share here will log "chat start" and none of those do.

So try to install the zip I share making a new project for it and in the install part select as in the bellow pic

![start_debug](https://user-images.githubusercontent.com/13755892/57654785-6b34f180-75ab-11e9-97a0-f0afeca52ff2.png)

image from
https://developer.samsung.com/tv/develop/getting-started/using-sdk/web-inspector

**Comment by itspeaky** [comment]
@fgl27 smarttv-twitch-default gets me this trying on differents channels .
![logdefault2](https://user-images.githubusercontent.com/50504232/57691586-e4345780-7644-11e9-863a-ca47459ec7f7.png)

smarttv-twitch-no_check shows this. 
![lognocheck1](https://user-images.githubusercontent.com/50504232/57691604-f3b3a080-7644-11e9-88d2-3c06f3ebe455.png)

**Comment by fgl27** [comment]
@itspeaky what happens when you in this line

https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/ChatLive.js#L145

change the "wss:" to just "ws:"

Remove one "s" from that line.

you can test that on any of those zip I share before.

Please log the result, thanks.

**Comment by itspeaky** [comment]
@fgl27 Seems to work fine changing that line. Tested it on the "smarttv-twitch-default" zip.
![wschanged](https://user-images.githubusercontent.com/50504232/57713834-89662480-7673-11e9-976e-4bd016a155b5.png)

**Comment by fgl27** [comment]
Ok I push the changes to fix the issue.

If anyone still has the issue and the version in about is **051419** let me know, if the version isn't that close the app by holding return key and reopen so it can update.
