### ISSUE TITLE
Light mode for chat

### ISSUE THREAD

**Issue by reconman** [fgl27/smarttv-twitch#122]
First of all, thank you for maintaining this app. Lately twitch doesn't play sound anymore in the Samsung TV browser, so this is a perfect alternative since Samsung seems dismissive with messages like "please contact twitch".

**Please describe the feature.**
I don't really like the black background with white font in the non-fullscreen mode. Is there a way to make the chat background white with black font?

The black borders at the top and bottom of the video will probably also need to be changed to white so the white chat fits better.

**Comment by fgl27** [comment]
> Is there a way to make the chat background white with black font?

Yes possible.

Will I make, no because will not be used why see bellow. Can some one add this as a feature? yes open source app.

Will look good, NO! why?

Samsung doesn't have o led TV meaning all they TV's have some sort of back light, if you are watching video that most scenes are very dark (a night scene for example) all the white from surrounding area will make very difficult to have a OK contrast and properly have a nice view experience.

That is why black border are used on any video that doesn't feet the TV not just on this app any video ever made (minus some odd artistic video).

But anyway this is a example on how to make it as featuring
https://github.com/fgl27/smarttv-twitch/commit/a5e1a0b8a3f58237bd3837fd802d323cbe603e7b

more is needed as a way to enable and disable it on a click.

This is a app that has it enable by default and can't be disable ever

[app.zip](https://github.com/fgl27/smarttv-twitch/files/4998521/app.zip)

that app has it enable by default all the time, chat will be enable and side by side mode by default the color have changed, is just for test and can be installed along side the release app without affecting it, so two apps will be installed for testing propuser.

**Comment by fgl27** [comment]
Added to the app TODO list.
