### ISSUE TITLE
Number of viewers on user menu

### ISSUE THREAD

**Issue by wylson2** [fgl27/smarttv-twitch#155]
In the older versions of the application it was possible to see the number of viewers in each game followed and only they appeared instead of all of them as now (games without any streamers appear now), is it possible for this feature to be implemented again?

![136111466_1108870332871802_1307975521016342718_n](https://user-images.githubusercontent.com/76911682/103483129-03589d80-4dc4-11eb-8dce-9e17ff619ba1.jpg)

TV Model: Ru7100

Thanks for the awesome app.

**Comment by fgl27** [comment]
I know, twitch doesn't provide today any open API to get followed games, they disabled a few weeks ago the one that had the full info, and they may disable the one the app is using any time soon as they don't support it.

This is something that is already part of the project TODO list https://github.com/fgl27/SmartTwitchTV/blob/master/apk/TODO.md#check-if-is-possible-to-re-add-some-removed-features because of that I will just close this.
