### ISSUE TITLE
Posibilty to change logo as square

### ISSUE THREAD

**Issue by tomo92s** [fgl27/smarttv-twitch#163]
May I have a please add posibility to change app icon as square? In Tizen Studio is square but after installing on TV is rectangular 
and it doesn't match the rest of the app.

**Comment by fgl27** [comment]
I update the installation process 

https://github.com/fgl27/smarttv-twitch#install-the-application

And add a new release

https://github.com/fgl27/smarttv-twitch/releases/download/4.0.1_V7/4.0.1_V7.zip

Use that and all must work OK, the issue was the app ID for some reason it must start with a letter so a square icon works, the above commit fixed it.

**Comment by tomo92s** [comment]
Now works perfect. Thanks ;)
