### ISSUE TITLE
Continue Watching Sync

### ISSUE THREAD

**Issue by PhantomProgram** [fgl27/smarttv-twitch#173]
I don't know the underlying data handling, but the Android Twitch app has a section called "Continue Watching" that groups the last 5 videos you watched as well as, I believe, live streams if you left mid-way through and keeps the time at which you left them allowing you to resume the video you had been watching or the vod of the livestream at the point you left. This also seems to sync with the browser to some extent as, while I don't know of a "Continue Watching" area in browser, it marks the progress and allows you to resume them when selecting videos.

I hoped it would be possible to sync the progress with the tv app by allowing you to resume from the point on the app and/or sync progress in the app with twitch itself (though the latter seems unlikely).
Thanks for your time, and sorry for the edit I mindlessly pressed ctrl-enter like a dunce.

**Comment by fgl27** [comment]
Twitch API that give access to what you wanna, are private, and can only be accessed via a Token that is generate when you access a official Twitch app site.

Because of that isn't possible to access it outside where it was generated.

You can only use the building history of the app... You can access it in the side panel click in the **user menu** option then navigate to **History**, on the top you can change to video, clips and live history.

But this history is all locally generated and has no way to sinckup with anything you watched outside the app.
