### ISSUE TITLE
Issue with update? 

### ISSUE THREAD

**Issue by ARAHTHUL** [fgl27/smarttv-twitch#190]
Hello! First, let me thank you for what you did with this awsome app! Keep up the good wotk! 

Now, I have a question: shoud I manually install or not? 
On my tv the app version is 4.0.1 may 19, 2021 and here it says the last one is july 1. The app didn't noticed me to update but it doesn't seem to do it itself, either. 

Tizen version: 3.0 | TV: UMU6100 | FW: T-KTMDEUC-1290.3

Thank you and have a nice day or night!

**Comment by fgl27** [comment]
The last time I change the app version was on may 19 see it here

https://github.com/fgl27/smarttv-twitch/blob/2eb616f8b174585f504743f3c473074eafd9de98/app/specific/Main.js#L123

As is wrote on the main read me https://github.com/fgl27/smarttv-twitch#updates

> This app can update itself 99% of the time, is a very simple process every time you open the app (when it is fully closed not running on the background) it will download the latest version of the app code from the repository, this way the installation process will only have to be redone after a major update where the changes are in the files from the release.zip, the app will warn the user if is needed to update it manually by performing the installation steps again.

When I release a new zip here https://github.com/fgl27/smarttv-twitch/releases and don't push a warning, is because the change is just a minor thing that doesn't demand update for example just check what is wrote on the release:

> 4.0.1.V9:
> **Fix square icon on TV that support it**
> All the commit history

If yours TV doesn't use square icon or if does and the icon is OK no need to install it again.

**Comment by ARAHTHUL** [comment]
Thank you fo your reply! I think it was a misunderstanding, you're right. Sorry bothering you! Have a nice one!
