### ISSUE TITLE
Chat synchronization in live stream

### ISSUE THREAD

**Issue by Goodfel** [fgl27/smarttv-twitch#25]
Hi,
Is there any way to adjust the synchronization of the chat in a live stream? It's a bit ahead of the stream.
Thanks for the app!
Regards

**Comment by fgl27** [comment]
Delay when a line of chat is display is possible, a little complicated on the code side but possible.

But do you know the exactly delay for it stream in relation to you?

Because it is different for it stream and for it viewer (as you can be on anywhere in the globe also the streamer) because of that there is no real way to automatic calculate in the code side (if there is let me know how), so this would be something that you would have to calculate and set for it stream.

but base on what would you calculate?


In controls you have this option

> Force refresh the Chat (in case it freezes or doesn't load): Force refresh the video by pressing select key twice, it will change the video quality to the same you are current watching, by opening information panel (first click) after second click will start re-buffering and the chat will reload it self

The above "resynchronizes" stream and chat, in case you pause it or it buffer too much and because of that another delay is added, but that only refresh it, doesn't add or remove any delay.

**Comment by fgl27** [comment]
Done, update pushed to use the update make shore to close the app so the app updates on next start.
