### ISSUE TITLE
Restoring VOD playback problems

### ISSUE THREAD

**Issue by someone30** [fgl27/smarttv-twitch#273]
When closing the app via the EXIT-key during VOD playback the restore point doesn't seem to get saved anymore. Reopening the app will then restart the VOD from the beginning or the last successfully saved restore point. The latter can (only?) be achieved by closing the playback via the RETURN-key.

Also: when fast forwarding a few times the playback sometimes jumps to the beginning or the last saved restore point. I'm not sure yet how to reproduce this but it regularly happens. It probably interrelates with the other problem. They both began to occur a few weeks (or months?) ago.

**Comment by someone30** [comment]
Correction: the first app closure via the EXIT-key will create a restore point per VOD. But after resuming the playback the restore point won't get updated when closing the app again (EXIT-key).

**Comment by fgl27** [comment]
I managed to test this minus the jump issue.

The restoring issue is resolved.

The jump may also be but I can't test I tried but here it always works...

I can think of a few scenarios where you try to jump and there is an issue...

Minor network issue and the player is unable to jump because of that the player resets, due to a player error the current time is lost and the player goes back to the last known value, on the prior app state that could be the last saved point, but now after the fixes, it will be the beginning of the stream or the time you just jump.

I'm unsure of the scenario that is causing this and what happens to the player, so test jumps and let me know, if it happens try to explain what the player did, long buffers, stall, something that can help understand what is going on.

**Comment by someone30** [comment]
Can confirm, restoring works now. Thank you!

The jumping issue will take a little bit longer to test. So far so good. When it happened there was no stall or anything. If at all the reaction time was maybe even a little bit quicker than normal. But I can't say for sure. I'll report back as soon as I have jumped through some longer VODs.

**Comment by someone30** [comment]
Nice, the jumping issue also seems to be fixed. :+1:
