### ISSUE TITLE
After restarting the TV, the app stays black

### ISSUE THREAD

**Issue by luisforque** [fgl27/smarttv-twitch#3]
Everything was working perfectly, until I had to turn off the TV (from the power)
After turning it back on, the app doesnt work. After clicking on it, it says "TwitchTv loading..." or something, and the whole screen goes black and nothing happens.

The other stuff seems to be working properly.

I **think** that the TV OS may have updated. Dont know if that would cause the bug, however. It seems to be either that, or when I turned off the TV, the app did not close properly and it is now on an inconsistent state.

**Comment by fgl27** [comment]
OK I understood.

The only things that can cause a problem like other then a TV bug, is if the app can't access the server to download the content.

So in order to check if your network has access to the server try to open this link:

http://tiny.cc/twitchkeycode

if you see this:

![screenshot from 2018-12-18 22-33-06](https://user-images.githubusercontent.com/13755892/50191419-fb308100-0314-11e9-80ef-9b2f452bce01.png)

Yours network is communicating OK with the server

That pages also opens in the TV browser, so for a complete test open the page on smartphone computer of yours choice if OK open on the TV.

If you can open the page just fine on the TV, then the app did go crazy, so the only way I can find to fix it is to reinstall it, using the computer.

If for some reason that fails try to fallow this "If it fail during the installation make shore you don't have any other Twitch.TV application installed on the TV, to uninstall the app manually, just open the "apps" application find all Twitch.TV app you have install in "my app" tab hold down the enter/select key on the top of the app and choose delete, after you have delete all Twitch.TV apps, try to install again."

If any other problem show up please post here, the reinstall of the app erases the app memory and is necessary o re add your user and keys.

:+1:

**Comment by luisforque** [comment]
I tested, and that page opened correctly on the pc and on the smartphone, but did not open on the tv... 
why is that?
anyway, I guess I will try to reinstall it later

**Comment by fgl27** [comment]
I don't know, is something on yours end restricting network access. Maybe yours home router blocking TV IP or something related.

You can always do a factory reset of the TV
https://www.samsung.com/au/support/tv-audio-video/smart-tv-how-to-perform-a-factory-data-reset/

**Comment by luisforque** [comment]
Just an fyi, I noticed that the issue only happens (and it happens frequently) if I close or minimize the app when leaving the app.
I noticed that it doesnt happen if you leave it open and selects other applications via the home button. Either the app stays open correctly, or it restarts correctly (when the tv force closes it).

**Comment by fgl27** [comment]
You have a internal internet issue (maybe external), that never happens to anyone else, at least not to me or I ever received a issue like this.

using the exit and close option is the same as let the app be forced closed by the TV or the same as holding the return key to actively force close it, minimize the app is the same as change to another app.

are basically TV functions so way the bug?

If you think there is a issue on the app that can be Address try to explain to me a way to reproduce the issue as I can't here with what you share, it never fails me, as long the internet is OK.

So recheck yours internet connection, yours TV connection to yours local internet, because I think is more related to that to anything related to how you exit the app.

**Comment by luisforque** [comment]
I dont think it is an issue with the internet, I think it may be related to the tv model and the software on the tv. 
I know its not related to the app, I mentioned this stuff because I thought maybe there would be any different implementation with those use cases, but if it happens only to me, dont worry about it

**Comment by luisforque** [comment]
Oi Felipe!
Sou brasileiro também. E sou desenvolvedor também. Até dei uma olhada por cima no código, mas não fui muito a fundo.
O app funciona de modo geral, apenas as vezes acontece esse erro que eu comentei.
O erro é que quando abro o app, ele fica em tela preta infinitamente. Isso acontece tanto quando ele estava minimizado e maximiza, quanto quando ele abre, ai aparece o "Twich loading......" e depois a tela fica escura.
Nesse cenário que eu comentei, de deixar ele aberto sempre, tinha parado de acontecer, por isso resolvi mencionar.
Não acho que seja problema de rede, o SO da tv eu posso passar pra vc quando chegar em casa.
Mas parece algo que não está sendo inicializado / terminado corretamente, alguma tela que não se carrega, algum botão que não se limpa, etc.
Que tipo de informações a mais você quer?
Abraço!
