### ISSUE TITLE
Application doesn't start up anymore

### ISSUE THREAD

**Issue by kaldonir** [fgl27/smarttv-twitch#44]
I''ve been using this app for quite some time, but yesterday it stopped working:

When trying to start the app, it just endlessly shows the rotating buffer icon. I have tried reinstalling the App, and the initial startup right during installation worked, but closing the app and reopening it resulted in the same issue. 

Opening the `index.html` file from the installed package on my PC loads everything correctly. 

Any tips on what to do / how to debug this?

**Comment by fgl27** [comment]
I update the app yesterday there is a lot of changes.
Here it is just working, doesn't mater how many times I close, this is probably something very specific you change when use the app, or from yours TV.

To debug the app the process is very simple, download the app from this link

https://github.com/fgl27/smarttv-twitch/archive/master.zip

And install that zip the same way you did the other, but this time instead of, do the normal install, you click on the lady bug icon on top panel of tizen it will make the app start on debug mode.

![Screenshot from 2019-08-02 10-43-31](https://user-images.githubusercontent.com/13755892/62374499-7e07f400-b512-11e9-9d78-b8e7d950da9b.png)

If everything start OK you will see something like this:

![Screenshot from 2019-08-02 10-45-15](https://user-images.githubusercontent.com/13755892/62374599-b4457380-b512-11e9-87f1-bba022dcfae6.png)

click on the **Console** tab to see the logs.

Now to reproduce the problem you can't close the app, because if you do the log will stop, but the app has a key that simulated a close and reopen of the app.

So to reproduce the bug, setup the app the same way you did before, changing the settings and enabling the chat, change the size, add a user etc etc, everything you did before that causes the issue and then request a refresh of the app by clicking on the B or green key, after the refresh the app will reload as if is opening and will show where in the app things are crashing, the key B can be pressed on any screen (when you are focus on the too of a thumbnails) or player, on settings or side panel it will not work.

show me the log result preferably share with me a txt file contains all the result of that window.

**Comment by fgl27** [comment]
I already found a load issue and fix it on the above, try the app again if the issue persist do what I ask and share the logs result.

**Comment by kaldonir** [comment]
Yes thank you, it works now.

**Comment by fgl27** [comment]
If something else happens let me know if is similar reopen this, if is something else open a new issue.
