### ISSUE TITLE
Low latency

### ISSUE THREAD

**Issue by markuznw** [fgl27/smarttv-twitch#51]
Hello, thanks for the wonderful app that made it possible to use my old Samsung TV with twitch ☺️

I wanted to ask if it's possible, somehow, to reproduce low latency mode as it is in chrome since most of my favorite streamers now use it so it's impossible to follow chat as it is kinda 30 seconds dedynched from video 😭

Thanks in advance!

**Comment by fgl27** [comment]
Is already enable by default

https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/Play.js#L489

fast_bread=true

if doesn't work is because it doesn't.

you can use chat delay option and fix the chat for you.
the max value a chat can be delay is 14s I believed, because twitch only keeps 28s of content available on a live stream and the player start to play on the half so you are technically most 14s benhide, a chat delay ins't something possible to calculate automatically, as there is those 14s plus wherever takes to parse the content and start the playback plus wherever is already the chat delay coming from twitch.

None of those have a way to get the real value is only assumptions.

So do you have a solution for the issue other then use a chat delay?

If not please close this.

**Comment by markuznw** [comment]
Thanks for the fast reply.

I didn't know it was already enabled as per currently I need to use computer to follow chat of the same stream as this extremely high delay makes TV totally unusable as said. So I guess it is reserved to desktop chrome and just doesn't work on TV.

Thanks anyway :) I'll close this as I'm not a Javascript developer and don't have any experience with twitch Apis so got no idea on how to help on technical part.

Let's hope in the future they'll allow for a better support for low latency :)

**Comment by fgl27** [comment]
you have a in app chat delay option how it is unusable, just add the delay you wanna and that is it already told you is most 14s.

**Comment by markuznw** [comment]
Chat delaying is not an option as I directly reply to the chat from another device (smartphone or tablet for example) and then just wanted the TV video stream to be on par with the chat like with computer.
Having a delay of 30s (or even 14s) means streamer is on a following action already when I send a text, so it makes the point of having the app on TV worthless for me

Don't know if you got my point :)
Would have been nice if it was technically doable to make stream on "low latency" like on Chrome so I thought you didn't enable that because it was either hard or time consuming, without considering maybe it was just not doable and limited to specific clients (with some sort of server detection on that).
That's the reason for this ticket, but I see having it already enable and just not working means there's probably no way for it on non official clients yet 😉

**Comment by fgl27** [comment]
[new.zip](https://github.com/fgl27/smarttv-twitch/files/3587775/new.zip)

There is a workaround, but I don't know how stable it is in terms of buffer, if will or will not start buffering and never stop, or over start calling buffer.

If you wanna try that let me know, you need to test for some days and let me know the result.

that zip installation the same as the release but if you don't delete the other you will have two, so don't confuse yourself. The one with a workaround show in about **APP Version: 4.0.1.TEST**

That is as close has one can get, I didn't find a streamer using low latency to test, be enable on the site doesn't mean that the streamer enable it as is showing enable to anyone but streamers say they aren't using.

if you are going to try just close this.

**Comment by fgl27** [comment]
Also set the live buffer in settings to 1, a lower buffer faster well start playing

**Comment by fgl27** [comment]
the line I have added is this

https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/Play.js#L763

technically anything higher didn't made positive difference, but maybe setting buffer to 1 and that from 24 to 26 may make it one second or two close to the best postion

I notice if I change that 24 to a too high value the stream may not load first time you open it, you may not notice but looking for the logs it did freeze and retry, with in reality is a setback in time as that "freeze and retry"  adds a dealy.

So if you wanna test that value and see what happens in the case you make the value bigger and get worst result try to lower it, everytime you install the app it resets it config so is necessary to add user set the buffer etc etc.

Test have fun.

**Comment by markuznw** [comment]
Hello Felipe, so after more than 10 days testing things my findings are the following:

- Latency is effectively reduced, it goes down to +5 seconds (compared to android twitch app) by using minimum buffer and other setting
- I got to use buffer 2 to make it "useable" because with 1 after a while it starts a buffer loop that makes it unwatchable (probably my wifi, even if AC, can't keep up with the flood)
- With buffer 2 and the other setting left as default latency is down to like +8/+10 seconds (with "stable" i get >+14) so it's definitely a NICE improvement without downsides for me

Thank you for providing the test file.
A question: do I have to just force close it to keep it updated or should I manually update it? I noticed the GUI is completely different so I guess that is from your new branch, but it seems I can find it only for android here on github?

Also I hope in the future some server side changes can "open" low latency up to be on par with, if not chrome, the twitch app itself. But this is still a big improvement as said ^^

**Comment by fgl27** [comment]
OK.

To keep the samsung version of the app update is only need to force close the app and it will selfe update, as long as you have installed the release version with is the zip that has a size of only 15kb or less.

![image](https://user-images.githubusercontent.com/13755892/65465114-d7fda980-de31-11e9-8502-5bcf12365a57.png)

The zip you download to test low latency does not self update it self ever, so you can use it and I let you know when I update the release to included this featuring.

The android version of this app from https://github.com/fgl27/SmartTwitchTV has a different user interface and has more featurings, that is because I do things there before and port it here after, I'm only one so I don't have time to keep all update as I wish I do when time is available.

The day I update the samsung version will look something like this:
https://fgl27.github.io/SmartTwitchTV/release/index.min.html

on the above the number 1 key of the keyboard is the back key.

So then it will have low latency as a option to easy enable disable it from the player controls as the android version of the app already has.

On the android version of the app I can keep the low latency position as close as possible is around +-1 second in relation to the website, as on android I have access to the player source I can mod it and control as I wish but on Tizen that is not the case.

But reading about recommendations on how to achieve low latency as a workaround is possible to improve this and the day I release I expect something between 1 to 3s in relation to the web site.

I probably release those changes next month and when I do will post here.

**Comment by fgl27** [comment]
@markuznw the low latency featured was merged on the release app.

It is technically better than the why I did before, test let me know.
