### ISSUE TITLE
Chat freezing

### ISSUE THREAD

**Issue by arrow759** [fgl27/smarttv-twitch#54]
Recently, chat has been freezing on VODs for me. Disabling and re-enabling chat doesn't fix it, only rewinding or fast forwarding does. This will only fix it for less than a minute though. This error has occurred on multiple streams, from multiple people.

Do you know of a fix for me or should I re-install the app?

**Comment by fgl27** [comment]
No.

can you provide a very specific way to replicate the issue?

Because if I can't replicate I can't fix, I didn't manage to do so by what you provide.

So replicate the problem on a very specific way more then once and let me know.

Those specific include, what VOD is, what the time of the VOD is, what you did before, fast forward/backward/ pause, exit and go back to the app, things that cause the chat to pause refresh etc, with it the thing causing the issue? exactly.

So provide all of that and I work on a solution.

**Comment by arrow759** [comment]
I have no idea how this occurred, it happened suddenly about 22 hours into a 30 hour VOD without me doing anything. This app has worked perfectly for three weeks until it yesterday. I've restarted my tv, opened brand new VODs, started from beginning, started from last location, VODs from different streamers. VODs from last week, VODs from last year. The bug persisted through it all. It doesn't affect current livestreams though.

I have no idea how this could be replicated.

**Comment by fgl27** [comment]
What is the app version in about?

Does it says TEST?

If yes you have the wrong app installed, as in the correct version the key B does noting.

**Comment by arrow759** [comment]
I just re-installed the app and chat is working again, I'll let you know if it happens again, hopefully I can identify the cause then.
