### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by kubi34** [fgl27/smarttv-twitch#71]
I tried v2 v3 v4 versions. I get Black screen error on tizen 2.3 (tizen studio 3.5)

**Comment by fgl27** [comment]
I don't get it. Black screen were?

Show me.

Only use V4 with tizen 3.5

**Comment by kubi34** [comment]
Black screen when launching app. Nothing happen only black screen. 
I use Tizen Studio 3.5. And my TV is 49ks8500 (tizen version: 2.3)

**Comment by fgl27** [comment]
You have a computer and a TV you didn't tell me where the black screen is did you...

OK I guess assuming the app install and when open doesn't load because it crashes...
It works here so must be something that the TV doesn't supports...

Install as a new project as I describe here 
https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

After share the log information that shows where the crash is..

**Comment by fgl27** [comment]
closed due to inactivity.
